project:
  type: website
  output-dir: docs

website: 
  title: "Hangcen Zou"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: awards.qmd
        text: Awards
      - href: cv.qmd
        text: CV
      - href: photography.qmd
        text: Photography

format: 
  html: 
    theme: minty
    mainfont: serif

